/**
 * Official Cosmetics Labelling Rules
 * Source: Cosmetics Rules, 2020 (G.S.R. 763(E))
 * Authority: Central Drugs Standard Control Organization (CDSCO), Ministry of Health and Family Welfare, Government of India
 */

export const cosmeticsRules = [
  {
    ruleId: 'COS-001',
    category: ['Cosmetics'],
    regulation: 'Rule 33',
    title: 'Licensed Manufacturing & Compliance Prohibition',
    requirement: 'Cosmetics manufactured in India must be manufactured under a valid license and labelled/packed in accordance with the Cosmetics Rules, 2020.',
    checkType: 'MANUFACTURING_LICENSE_COMPLIANCE',
    severity: 'HIGH',
    officialSource: 'Cosmetics Rules, 2020',
    sourceAuthority: 'CDSCO, Ministry of Health and Family Welfare, Government of India',
    officialUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/Cosmetics-Rules-2020.pdf',
    active: true,
  },
  {
    ruleId: 'COS-002',
    category: ['Cosmetics'],
    regulation: 'Rule 34(1)(a)',
    title: 'Name of the Cosmetic Product',
    requirement: 'The name of the cosmetic commodity must be clearly and prominently printed on both the inner and outer labels.',
    checkType: 'COSMETIC_NAME',
    severity: 'CRITICAL',
    officialSource: 'Cosmetics Rules, 2020',
    sourceAuthority: 'CDSCO, Ministry of Health and Family Welfare, Government of India',
    officialUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/Cosmetics-Rules-2020.pdf',
    active: true,
  },
  {
    ruleId: 'COS-003',
    category: ['Cosmetics'],
    regulation: 'Rule 34(1)(b)',
    title: 'Name and Complete Address of Manufacturer',
    requirement: 'The name of the manufacturer and complete address of the premises where the cosmetic was manufactured must be stated on the label.',
    checkType: 'COSMETIC_MANUFACTURER_ADDRESS',
    severity: 'CRITICAL',
    officialSource: 'Cosmetics Rules, 2020',
    sourceAuthority: 'CDSCO, Ministry of Health and Family Welfare, Government of India',
    officialUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/Cosmetics-Rules-2020.pdf',
    active: true,
  },
  {
    ruleId: 'COS-004',
    category: ['Cosmetics'],
    regulation: 'Rule 34(1)(c)',
    title: 'Use Before / Expiry Date Marking',
    requirement: 'An expiry date or "Use before" followed by the month and year must be declared on both inner and outer labels.',
    checkType: 'COSMETIC_EXPIRY_DATE',
    severity: 'CRITICAL',
    officialSource: 'Cosmetics Rules, 2020',
    sourceAuthority: 'CDSCO, Ministry of Health and Family Welfare, Government of India',
    officialUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/Cosmetics-Rules-2020.pdf',
    active: true,
  },
  {
    ruleId: 'COS-005',
    category: ['Cosmetics'],
    regulation: 'Rule 34(2)(a)',
    title: 'Batch Number / Lot Identification',
    requirement: 'A distinctive batch number preceded by the letter "B" or "Batch No." must be declared on the label (subject to small-container exceptions).',
    checkType: 'COSMETIC_BATCH_NUMBER',
    severity: 'HIGH',
    officialSource: 'Cosmetics Rules, 2020',
    sourceAuthority: 'CDSCO, Ministry of Health and Family Welfare, Government of India',
    officialUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/Cosmetics-Rules-2020.pdf',
    active: true,
  },
  {
    ruleId: 'COS-006',
    category: ['Cosmetics'],
    regulation: 'Rule 34(2)(b)',
    title: 'Manufacturing Licence Number (M.L. / Reg No.)',
    requirement: 'Manufacturing licence number preceded by the letter "M." or "Mfg. Lic. No." or CDSCO import registration certificate must be stated.',
    checkType: 'COSMETIC_LICENSE_NUMBER',
    severity: 'CRITICAL',
    officialSource: 'Cosmetics Rules, 2020',
    sourceAuthority: 'CDSCO, Ministry of Health and Family Welfare, Government of India',
    officialUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/Cosmetics-Rules-2020.pdf',
    active: true,
  },
  {
    ruleId: 'COS-007',
    category: ['Cosmetics'],
    regulation: 'Rule 34(3)',
    title: 'Outer Label Net Contents Declaration',
    requirement: 'The outer label must declare net contents in metric units: weight for solids, fluid measure for liquids, or weight/fluid measure for semi-solids.',
    checkType: 'COSMETIC_NET_CONTENTS',
    severity: 'CRITICAL',
    officialSource: 'Cosmetics Rules, 2020',
    sourceAuthority: 'CDSCO, Ministry of Health and Family Welfare, Government of India',
    officialUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/Cosmetics-Rules-2020.pdf',
    active: true,
  },
  {
    ruleId: 'COS-008',
    category: ['Cosmetics'],
    regulation: 'Rule 34(4)',
    title: 'Directions for Safe Use, Warnings & Hazardous Ingredients',
    requirement: 'Where a hazard exists, the label must provide adequate directions for safe use, warnings, cautions, and names/quantities of hazardous substances.',
    checkType: 'SAFE_USE_WARNINGS',
    severity: 'HIGH',
    officialSource: 'Cosmetics Rules, 2020',
    sourceAuthority: 'CDSCO, Ministry of Health and Family Welfare, Government of India',
    officialUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/Cosmetics-Rules-2020.pdf',
    active: true,
  },
  {
    ruleId: 'COS-009',
    category: ['Cosmetics'],
    regulation: 'Rule 34(7)',
    title: 'Ingredients Declaration in Descending Order',
    requirement: 'Ingredients present in concentration greater than 1% must be listed in descending order of weight or volume, followed by those at or below 1%.',
    checkType: 'COSMETIC_INGREDIENTS_ORDER',
    severity: 'HIGH',
    officialSource: 'Cosmetics Rules, 2020',
    sourceAuthority: 'CDSCO, Ministry of Health and Family Welfare, Government of India',
    officialUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/Cosmetics-Rules-2020.pdf',
    active: true,
  },
  {
    ruleId: 'COS-010',
    category: ['Cosmetics'],
    regulation: 'Rule 36',
    title: 'Prohibition of False or Exaggerated Cosmetic Claims',
    requirement: 'No cosmetic label shall make false or exaggerated claims regarding therapeutic efficacy or physiological effects.',
    checkType: 'COSMETIC_CLAIMS_PROHIBITION',
    severity: 'MEDIUM',
    officialSource: 'Cosmetics Rules, 2020',
    sourceAuthority: 'CDSCO, Ministry of Health and Family Welfare, Government of India',
    officialUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/Cosmetics-Rules-2020.pdf',
    active: true,
  },
  {
    ruleId: 'COS-011',
    category: ['Cosmetics'],
    regulation: 'Rule 38',
    title: 'Toothpaste Fluoride Content Declaration & Date Marking',
    requirement: 'Fluoride-containing dental products must declare the exact fluoride content in ppm on the label alongside mandatory expiry date.',
    checkType: 'FLUORIDE_TOOTHPASTE_DECLARATION',
    severity: 'HIGH',
    officialSource: 'Cosmetics Rules, 2020',
    sourceAuthority: 'CDSCO, Ministry of Health and Family Welfare, Government of India',
    officialUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/Cosmetics-Rules-2020.pdf',
    active: true,
  },
  {
    ruleId: 'COS-012',
    category: ['Cosmetics'],
    regulation: 'Rule 39',
    title: 'Compliance with Bureau of Indian Standards (BIS)',
    requirement: 'Cosmetics must comply with the specifications laid down in the Ninth Schedule and applicable Bureau of Indian Standards (BIS).',
    checkType: 'BIS_STANDARDS_SPECIFICATION',
    severity: 'MEDIUM',
    officialSource: 'Cosmetics Rules, 2020 & Ninth Schedule',
    sourceAuthority: 'Bureau of Indian Standards (BIS) & CDSCO',
    officialUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/Cosmetics-Rules-2020.pdf',
    active: true,
  },
];
