/**
 * Official FSSAI Food Labelling & Display Rules
 * Source: Food Safety and Standards (Labelling and Display) Regulations, 2020 & Product Standards
 * Authority: Food Safety and Standards Authority of India (FSSAI)
 */

export const foodRules = [
  {
    ruleId: 'FOOD-001',
    category: ['Food'],
    regulation: 'Regulation 4',
    title: 'General Prohibition of Misleading / Deceptive Claims',
    requirement: 'Labelling information shall not be false, misleading, or deceptive, or likely to create an erroneous impression regarding the character of food.',
    checkType: 'MISLEADING_PROHIBITION',
    severity: 'HIGH',
    officialSource: 'Food Safety and Standards (Labelling and Display) Regulations, 2020',
    sourceAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    officialUrl: 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Labelling_Display_23_09_2021.pdf',
    active: true,
  },
  {
    ruleId: 'FOOD-002',
    category: ['Food'],
    regulation: 'Regulation 5(1)',
    title: 'True Nature and Name of Food',
    requirement: 'Every package of food shall carry the name of the food which indicates the true nature of the food commodity.',
    checkType: 'FOOD_NAME',
    severity: 'CRITICAL',
    officialSource: 'Food Safety and Standards (Labelling and Display) Regulations, 2020',
    sourceAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    officialUrl: 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Labelling_Display_23_09_2021.pdf',
    active: true,
  },
  {
    ruleId: 'FOOD-003',
    category: ['Food'],
    regulation: 'Regulation 5(2)',
    title: 'Mandatory List of Ingredients',
    requirement: 'A complete list of ingredients shall be declared in descending order of their in-going weight or volume (m/m or v/v) at the time of manufacture.',
    checkType: 'INGREDIENTS_LIST',
    severity: 'CRITICAL',
    officialSource: 'Food Safety and Standards (Labelling and Display) Regulations, 2020',
    sourceAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    officialUrl: 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Labelling_Display_23_09_2021.pdf',
    active: true,
  },
  {
    ruleId: 'FOOD-004',
    category: ['Food'],
    regulation: 'Regulation 5(3)',
    title: 'Nutritional Information Declaration',
    requirement: 'Nutritional information per 100g or per 100ml or per single consumption pack must be declared (energy, protein, carbohydrate, total sugars, added sugars, total fat, saturated fat, trans fat, sodium).',
    checkType: 'NUTRITIONAL_INFO',
    severity: 'HIGH',
    officialSource: 'Food Safety and Standards (Labelling and Display) Regulations, 2020',
    sourceAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    officialUrl: 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Labelling_Display_23_09_2021.pdf',
    active: true,
  },
  {
    ruleId: 'FOOD-005',
    category: ['Food'],
    regulation: 'Regulation 5(4)',
    title: 'Vegetarian / Non-Vegetarian Logo Declaration',
    requirement: 'Every package of food shall bear the green filled circle inside a green square (Vegetarian) or brown triangle inside a brown square (Non-Vegetarian).',
    checkType: 'VEG_NON_VEG_LOGO',
    severity: 'CRITICAL',
    officialSource: 'Food Safety and Standards (Labelling and Display) Regulations, 2020',
    sourceAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    officialUrl: 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Labelling_Display_23_09_2021.pdf',
    active: true,
  },
  {
    ruleId: 'FOOD-006',
    category: ['Food'],
    regulation: 'Regulation 5(5)',
    title: 'Declaration Regarding Food Additives & Flavourings',
    requirement: 'Declarations for permitted food additives (INS numbers or functional class) and nature identical / synthetic flavourings must be stated.',
    checkType: 'ADDITIVES_FLAVOURINGS',
    severity: 'MEDIUM',
    officialSource: 'Food Safety and Standards (Labelling and Display) Regulations, 2020',
    sourceAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    officialUrl: 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Labelling_Display_23_09_2021.pdf',
    active: true,
  },
  {
    ruleId: 'FOOD-007',
    category: ['Food'],
    regulation: 'Regulation 5(6)',
    title: 'Name and Complete Address of Brand Owner / Manufacturer',
    requirement: 'Name and complete address of manufacturer / packer / brand owner must be displayed using qualifying words such as "Manufactured by", "Marketed by", or "Packed by".',
    checkType: 'BRAND_OWNER_DETAILS',
    severity: 'CRITICAL',
    officialSource: 'Food Safety and Standards (Labelling and Display) Regulations, 2020',
    sourceAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    officialUrl: 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Labelling_Display_23_09_2021.pdf',
    active: true,
  },
  {
    ruleId: 'FOOD-008',
    category: ['Food'],
    regulation: 'Regulation 5(7)',
    title: 'FSSAI Logo and 14-Digit Licence Number',
    requirement: 'The FSSAI logo and 14-digit licence number of the manufacturer or brand owner must be prominently displayed on the label.',
    checkType: 'FSSAI_LOGO_LICENSE',
    severity: 'CRITICAL',
    officialSource: 'Food Safety and Standards (Labelling and Display) Regulations, 2020',
    sourceAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    officialUrl: 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Labelling_Display_23_09_2021.pdf',
    active: true,
  },
  {
    ruleId: 'FOOD-009',
    category: ['Food'],
    regulation: 'Regulation 5(8)',
    title: 'Net Quantity, MRP, and Consumer Care (Harmonized)',
    requirement: 'Net quantity, retail sale price (MRP), and consumer care details must strictly conform to the Legal Metrology (Packaged Commodities) Rules, 2011.',
    checkType: 'HARMONIZED_LEGAL_METROLOGY',
    severity: 'CRITICAL',
    officialSource: 'Food Safety and Standards (Labelling and Display) Regulations, 2020',
    sourceAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    officialUrl: 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Labelling_Display_23_09_2021.pdf',
    active: true,
  },
  {
    ruleId: 'FOOD-010',
    category: ['Food'],
    regulation: 'Regulation 5(9)',
    title: 'Lot / Code / Batch Identification',
    requirement: 'A batch number or code number or lot number by which the food can be traced in manufacture and identified in distribution shall be given.',
    checkType: 'BATCH_IDENTIFICATION',
    severity: 'HIGH',
    officialSource: 'Food Safety and Standards (Labelling and Display) Regulations, 2020',
    sourceAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    officialUrl: 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Labelling_Display_23_09_2021.pdf',
    active: true,
  },
  {
    ruleId: 'FOOD-011',
    category: ['Food'],
    regulation: 'Regulation 5(10)',
    title: 'Date Marking (Date of Mfg / Expiry / Best Before)',
    requirement: 'The "Date of manufacture or packaging" and "Expiry Date" or "Best Before Date" must be declared in prescribed format.',
    checkType: 'DATE_MARKING',
    severity: 'CRITICAL',
    officialSource: 'Food Safety and Standards (Labelling and Display) Regulations, 2020',
    sourceAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    officialUrl: 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Labelling_Display_23_09_2021.pdf',
    active: true,
  },
  {
    ruleId: 'FOOD-012',
    category: ['Food'],
    regulation: 'FSSAI Product-Specific Regulations',
    title: 'Standardized Food Category Compliance',
    requirement: 'Product must conform to applicable Food Products Standards and Food Additives regulations specific to its standardized classification.',
    checkType: 'STANDARDIZED_FOOD_STANDARD',
    severity: 'MEDIUM',
    officialSource: 'Food Safety and Standards (Food Products Standards and Food Additives) Regulations, 2011',
    sourceAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    officialUrl: 'https://www.fssai.gov.in/upload/uploadfiles/files/Compendium_Food_Additives_Regulations_08_09_2020.pdf',
    active: true,
  },
];
