/**
 * Official Household Products Labelling Rules
 * Primary Source: Legal Metrology (Packaged Commodities) Rules, 2011 & Applicable BIS Standards
 * Authority: Department of Consumer Affairs & Bureau of Indian Standards, Government of India
 */

export const householdRules = [
  {
    ruleId: 'HH-001',
    category: ['Household'],
    regulation: 'Rule 6(1)(a)',
    title: 'Manufacturer / Packer / Brand Identity',
    requirement: 'Name and complete physical address of the manufacturer, packer, or marketer of the household product must be declared.',
    checkType: 'HH_MANUFACTURER_DECLARATION',
    severity: 'CRITICAL',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'HH-002',
    category: ['Household'],
    regulation: 'Rule 6(1)(b)',
    title: 'Generic Name of Household Cleaning / Consumer Commodity',
    requirement: 'The common or generic name of the household chemical/cleaning commodity (e.g., Detergent Powder, Liquid Dishwash, Floor Cleaner) must be explicitly stated.',
    checkType: 'HH_GENERIC_NAME',
    severity: 'CRITICAL',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'HH-003',
    category: ['Household'],
    regulation: 'Rule 6(1)(c)',
    title: 'Net Quantity in Metric Units',
    requirement: 'Net quantity must be declared in standard metric units of weight (g, kg), volume (ml, L), or piece count.',
    checkType: 'HH_NET_QUANTITY',
    severity: 'CRITICAL',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'HH-004',
    category: ['Household'],
    regulation: 'Rule 6(1)(d)',
    title: 'Month and Year of Manufacture / Packing',
    requirement: 'Month and year of manufacture or pre-packing must appear on the package.',
    checkType: 'HH_MFG_DATE',
    severity: 'HIGH',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'HH-005',
    category: ['Household'],
    regulation: 'Rule 6(1)(e)',
    title: 'Maximum Retail Price (MRP) Declaration',
    requirement: 'Retail sale price of the package in Indian currency (INR / Rs.) inclusive of all taxes must be declared.',
    checkType: 'HH_MRP_DECLARATION',
    severity: 'CRITICAL',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'HH-006',
    category: ['Household'],
    regulation: 'Rule 6(1-A)',
    title: 'Customer Care Cell Contact Details',
    requirement: 'Name, address, contact phone number, and email of the consumer care executive must be clearly printed.',
    checkType: 'HH_CONSUMER_CARE',
    severity: 'HIGH',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'HH-007',
    category: ['Household'],
    regulation: 'Rule 6(11)',
    title: 'Unit Sale Price Declaration',
    requirement: 'Unit sale price declared as Rs. per g / kg / ml / L / piece where package weight exceeds standard threshold.',
    checkType: 'HH_UNIT_SALE_PRICE',
    severity: 'MEDIUM',
    officialSource: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2021',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'HH-008',
    category: ['Household'],
    regulation: 'Applicable Safety / BIS Standard (e.g. IS 4955 / IS 286)',
    title: 'Safe Usage Directions & Precautionary Warnings',
    requirement: 'Adequate precautionary warnings (e.g., "Keep out of reach of children", "Avoid contact with eyes") and usage directions must be given for chemical household cleaners.',
    checkType: 'HH_SAFETY_WARNINGS',
    severity: 'HIGH',
    officialSource: 'Bureau of Indian Standards & Consumer Protection Act',
    sourceAuthority: 'Central Consumer Protection Authority (CCPA) / BIS',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/consumer-protection-act-2019',
    active: true,
  },
];
