/**
 * Official Legal Metrology Rules
 * Source: Legal Metrology Act, 2009; Legal Metrology (Packaged Commodities) Rules, 2011 & Amendments
 * Authority: Department of Consumer Affairs, Government of India
 */

export const legalMetrologyRules = [
  {
    ruleId: 'LM-001',
    category: ['Food', 'Edible Oil', 'Cosmetics', 'Household'],
    regulation: 'Rule 6(1)(a)',
    title: 'Name and Address of Manufacturer / Packer / Importer',
    requirement: 'Name and complete address of the manufacturer, or packer, or importer must be clearly declared.',
    checkType: 'MANUFACTURER_DECLARATION',
    severity: 'CRITICAL',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'LM-002',
    category: ['Food', 'Edible Oil', 'Cosmetics', 'Household'],
    regulation: 'Rule 6(1)(b)',
    title: 'Common or Generic Name of the Commodity',
    requirement: 'Common or generic name of the commodity contained in the package must be prominently declared.',
    checkType: 'COMMODITY_NAME',
    severity: 'CRITICAL',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'LM-003',
    category: ['Food', 'Edible Oil', 'Cosmetics', 'Household'],
    regulation: 'Rule 6(1)(c)',
    title: 'Net Quantity Declaration in Standard Metric Units',
    requirement: 'Net quantity in standard metric units of weight (g, kg), measure (ml, L), or piece number must be declared.',
    checkType: 'NET_QUANTITY',
    severity: 'CRITICAL',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'LM-004',
    category: ['Food', 'Edible Oil', 'Cosmetics', 'Household'],
    regulation: 'Rule 6(1)(d)',
    title: 'Month and Year of Manufacture / Packing',
    requirement: 'Month and year in which the commodity is manufactured or pre-packed must be clearly stated.',
    checkType: 'MFG_DATE',
    severity: 'HIGH',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'LM-005',
    category: ['Food', 'Edible Oil', 'Cosmetics', 'Household'],
    regulation: 'Rule 6(1)(e)',
    title: 'Maximum Retail Price (MRP) Declaration',
    requirement: 'Retail sale price of the package in Indian currency (INR / Rs.) inclusive of all taxes must be declared.',
    checkType: 'MRP_DECLARATION',
    severity: 'CRITICAL',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'LM-006',
    category: ['Food', 'Edible Oil', 'Cosmetics', 'Household'],
    regulation: 'Rule 6(1-A)',
    title: 'Consumer Care Contact Information',
    requirement: 'Name, address, telephone number, and email address of the person or office to be contacted in case of consumer complaints.',
    checkType: 'CONSUMER_CARE',
    severity: 'HIGH',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'LM-007',
    category: ['Food', 'Edible Oil', 'Cosmetics', 'Household'],
    regulation: 'Rule 6(10) / Rule 6',
    title: 'Country of Origin Declaration (Imported Products)',
    requirement: 'Name of the country of origin or manufacture must be declared on packages, specifically when imported.',
    checkType: 'COUNTRY_OF_ORIGIN',
    severity: 'HIGH',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'LM-008',
    category: ['Food', 'Edible Oil', 'Cosmetics', 'Household'],
    regulation: 'Rule 6(11)',
    title: 'Unit Sale Price Declaration',
    requirement: 'Unit Sale Price in prescribed format (e.g., Rs. per g, Rs. per kg, Rs. per ml, Rs. per L, or Rs. per number) where applicable.',
    checkType: 'UNIT_SALE_PRICE',
    severity: 'MEDIUM',
    officialSource: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2021',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'LM-009',
    category: ['Food', 'Edible Oil', 'Cosmetics', 'Household'],
    regulation: 'Rule 8',
    title: 'Principal Display Panel Declarations Placement',
    requirement: 'Mandatory declarations must be grouped together on the principal display panel in the prescribed layout.',
    checkType: 'PRINCIPAL_DISPLAY_PANEL',
    severity: 'MEDIUM',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'LM-010',
    category: ['Food', 'Edible Oil', 'Cosmetics', 'Household'],
    regulation: 'Rule 9(1)(a)',
    title: 'Legibility and Prominence of Declarations',
    requirement: 'All declarations on a package shall be unambiguous, conspicuous, legible, and have sufficient color contrast.',
    checkType: 'LEGIBILITY_PROMINENCE',
    severity: 'MEDIUM',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'LM-011',
    category: ['Food', 'Edible Oil', 'Cosmetics', 'Household'],
    regulation: 'Rule 9',
    title: 'Language of Declarations (Hindi / English)',
    requirement: 'Declarations must be in Hindi (Devanagari script) or in English, with optional additional languages.',
    checkType: 'LANGUAGE_COMPLIANCE',
    severity: 'MEDIUM',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'LM-012',
    category: ['Food', 'Edible Oil', 'Cosmetics', 'Household'],
    regulation: 'Rule 18',
    title: 'Retail Package Compliance Provisions',
    requirement: 'Retail packages must not exceed authorized maximum retail pricing or omit standard metric declarations.',
    checkType: 'RETAIL_PACKAGE_PROVISIONS',
    severity: 'MEDIUM',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
  {
    ruleId: 'LM-013',
    category: ['Food', 'Edible Oil', 'Cosmetics', 'Household'],
    regulation: 'Rule 24',
    title: 'Wholesale Package Exemption / Provisions',
    requirement: 'Wholesale package rules apply solely to packages intended for intermediaries, not ordinary retail packages.',
    checkType: 'WHOLESALE_PROVISIONS',
    severity: 'LOW',
    officialSource: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceAuthority: 'Department of Consumer Affairs, Government of India',
    officialUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/the-legal-metrology-packaged-commodities-rules-2011',
    active: true,
  },
];
